[package]
name = "woodpecker"
version = "1.0.0"
edition = "2024"
description = "Command-line To-Do list application."
repository = "https://github.com/v0idx/woodpecker"
license = "BSD-2-Clause"
categories = ["command-line-utilities"]
keywords = ["utility", "todo", "todo-list"]

[dependencies]
app_dirs2 = "2.5.5"
chrono = { version = "0.4.45", features = ["serde"] }
clap = { version = "4.6.7", features = ["derive"] }
clap_derive = "4.6.7"
rmp-serde = "1.3.1"
serde = { version = "1.0.229", features = ["derive"] }
